[project]
name = "vision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.6"
dependencies = [
    "fastapi>=0.123.0",
    "fer>=25.10.3",
    "mediapipe>=0.10.14",
    "opencv-python>=4.12.0.88",
    "uvicorn>=0.38.0",
]
