[project]
name = "audio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.123.0",
    "faster-whisper>=1.2.1",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]
